#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M3{1,0,17.9,0
#
tags-cc1310.xem3: package/cfg/tags-cc1310.xem3.mak

clean::
	-$(RM) package/cfg/tags-cc1310.xem3.mak
